In [1]:
import numpy as np

In [2]:
#Datos
A = np.array([[2,3],[5,7],[11,13]])
B = np.array([[1,3],[2,1]])
C = np.array([[3,1],[4,2]])

In [3]:
# Asociativa
#El resultado es el mismo no importa el orden
#A*(B*C)=A*(B*C)  
ABC = A.dot(B.dot(C))
print(ABC)

[[ 60  26]
 [145  63]
 [295 129]]


In [4]:
AB_C = A.dot(B).dot(C)
print(AB_C)

[[ 60  26]
 [145  63]
 [295 129]]


In [5]:
#Distrbutiva
#A*(B+C) = (A*B)+(A*C)
D = A.dot(B+C)
E = (A.dot(B))+(A.dot(C))

In [6]:
print(D)
print(E)

[[ 26  17]
 [ 62  41]
 [122  83]]
[[ 26  17]
 [ 62  41]
 [122  83]]


In [7]:
#Otra forma de comparar los resultados
print(D==E)

[[ True  True]
 [ True  True]
 [ True  True]]


In [8]:
#Conmutativa (no aplica para matrices)
#B*C = C*B

In [9]:
F = B.dot(C)
G = C.dot(B)

In [10]:
print(F==G)

[[False False]
 [False False]]


In [11]:
print(F)

[[15  7]
 [10  4]]


In [12]:
print(G)

[[ 5 10]
 [ 8 14]]


In [16]:
#Conmutativa - si aplica para vectores
v1 = np.array([[2],[7]])
v2 = np.array([[3],[5]])

In [17]:
#Para hacer esta multiplicación es necesario transponer
v1_tv2 = v1.T.dot(v2)
v2_tv1 = v2.T.dot(v1)

In [18]:
print(v1_tv2)

[[41]]


In [19]:
print(v2_tv1)

[[41]]
