In [1]:
import numpy as np

In [2]:
#Datos
A = np.array([[2,3],[5,7],[11,13]])
B = np.array([[1,3],[2,1]])

In [3]:
print(A)

[[ 2  3]
 [ 5  7]
 [11 13]]


In [4]:
print(B)

[[1 3]
 [2 1]]


In [5]:
#AB transpuesta = A producto interno B todo transpuesto
AB_t = A.dot(B).T

In [6]:
#B transpuesto producto interno A transpuesto
B_tA_t = B.T.dot(A.T)

In [7]:
#Validar igualdad de operaciones
print(AB_t == B_tA_t)

[[ True  True  True]
 [ True  True  True]]


In [8]:
print(AB_t)

[[ 8 19 37]
 [ 9 22 46]]


In [9]:
print(B_tA_t)

[[ 8 19 37]
 [ 9 22 46]]
